### ISSUE TITLE
Create PCB does not work on 18.4 

### ISSUE THREAD

**Issue by db5fp** [marmni/FreeCAD-PCB#29]
Hi,

maybe I'm stupid, but I cannot creat a new PCB with freecad 18.4 and last BCB-Adon.
Is there any tutorila or Howto?
I need at frist an PCB-Layot for a HF-Design that ist not possile to be done in KiCAD.

Best regards
Frank

**Comment by marmni** [comment]
Hi,
in the PCB folder you will find instructions (subfolder / instructions). They are old or unfinished - but that's all for now.

What's the problem?
