### ISSUE TITLE
Support for other PCB formats?

### ISSUE THREAD

**Issue by bob-u** [marmni/FreeCAD-PCB#30]
Hi

I think great idea for EDA software to 'outsource' 3D part to proper CAD tools.  Even though there's rudimentary support for 3D viewing within Horizon EDA, have you considered supporting that program?

**Comment by marmni** [comment]
Hi,
this is not a problem if the file format is open - in this case I see that it is. However, at the moment I prefer to focus on getting rid of errors

**Comment by bob-u** [comment]
Thank you for looking into it.  I have learned since that Horizon EDA can export to STEP file.
