### ISSUE TITLE
Feature Request - Dereference attributes

### ISSUE THREAD

**Issue by Wiredhome** [marmni/FreeCAD-PCB#31]
In an Eagle design, I can create global attributes 
![image](https://user-images.githubusercontent.com/13155300/86523147-a9cfe000-be2d-11ea-85e3-3e4ddc2ef8fd.png)

Then on the PCB, I can place some text, perhaps in the top document layer, that references the attribute.
![image](https://user-images.githubusercontent.com/13155300/86523167-092df000-be2e-11ea-9b30-c0372f8d81e7.png)

This is basically the same as the Name and Value on a component - other than where in the .brd structure it is.
FreeCAD-PCB does not dereference the attribute, so the silk screen on the PCB looks like this:
![image](https://user-images.githubusercontent.com/13155300/86523185-688c0000-be2e-11ea-9f30-ee4bacec3cc9.png)

In the .brd XML, here's the global attributes definition:
```
...
</libraries>
<attributes>
<attribute name="PRODUCT" value="Power Supply"/>
<attribute name="VERSION" value="0.1"/>
</attributes>
<variantdefs>
...
```

And actually upward in the file is the reference to these attributes:
```
...
<board>
<plain>
<wire x1="0" y1="0" x2="127" y2="0" width="0" layer="20"/>
<wire x1="127" y1="0" x2="127" y2="76" width="0" layer="20"/>
<wire x1="127" y1="76" x2="0" y2="76" width="0" layer="20"/>
<wire x1="0" y1="76" x2="0" y2="0" width="0" layer="20"/>
<hole x="5.6" y="5.6" drill="3.8"/>
<hole x="5.6" y="70.4" drill="3.8"/>
<hole x="121.4" y="70.4" drill="3.8"/>
<hole x="121.4" y="5.6" drill="3.8"/>
<text x="16.8" y="6.6" size="1.778" layer="21">&gt;PRODUCT</text>
<text x="16.7" y="3" size="1.778" layer="21">&gt;VERSION</text>
</plain>
<libraries>
...
```

Is this an easy enhancement?

I am competent in software, but have never authored Python, so I find it esaier to read than to write. I was browsing into eagle.py, and in my version, starting at line 149:
```
    def getPCB(self, borderObject):
        dane = self.getSection('plain')
        
        for i in self.getWires(dane, 20):
```

It looks like it could use an iterator like:
```
        for i in self.getTexts(dane, 20):
```

But from here I'm a bit out of my area of expertise, and I don't see a method for debugging other than FreeCAD.Console.PrintWarning, so I think it will take me some time to stumble up against a few dead-ends before I find a path forward.

**Comment by marmni** [comment]
Hi,
added.

**Comment by Wiredhome** [comment]
**Phenomenal!** and so much simpler than what was in my imagination. 

![image](https://user-images.githubusercontent.com/13155300/86544994-08aa5d80-bef1-11ea-94b8-c68b12cd452a.png)

Thanks!
