### ISSUE TITLE
Updating FreeCAD-PCB WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [marmni/FreeCAD-PCB#4]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@marmni hi, just checking in since it looks like there is activity on this repo's 0.18 branch. Can you share what you're working on and what you intention for it is? Will it be compatible with FreeCAD v0.19 as well ?

**Comment by marmni** [comment]
Hi,
at the moment I'm "fighting" with some old errors. Current version (branch 0.18) is fully usable and compatible with FC0.18, but at the moment it should be treated as a beta version. Some changes block backwards compatibility (day by day).

Major issues are currently resolved and I plan to release this version in a few weeks. After then I will check FC0.19.

**Comment by luzpaz** [comment]
Fantastic!

**Comment by marmni** [comment]
Hi,
at the moment these topics are prio and after solving them I will release final version:
- reimplementation names/values parameter for the parts
- 'Cut holes through all layers' - eliminate problems after reloading saved *.FCStd file
- reimplementation of the KiCAD importer/exporter.
- IDF importer - contour direction detection to avoid errors during importing a board

**Comment by Wiredhome** [comment]
Hi Marmni, I have FC 0.18.4, and the latest FC-PCB with the updates from 3 days ago. The parts render nicely, but the board itself is not shown [Eagle]. I see this effect with the PCB\examples\example_1.brd as well as my own. My earlier combination FC 0.18 and the earlier FC-PCB for 0.18 did render the PCB, but with the known issues of the earlier combo.
Any thoughts for which file I could look at and compare to the older version?

**Comment by marmni** [comment]
Hi,
I do not see any problems with rendering boards on FC 0.18.4. But to be sure, I sent all the files again. Please check now. Do you use win or linux?

**Comment by Wiredhome** [comment]
**Fixed! And I'd say the best integration yet.**

[I'm on Win10.] I tried merging, but ended up with remove/reinstall FC 0.18.4 and then your latest integration, and it looks very good.

![myboard](https://user-images.githubusercontent.com/13155300/71328614-94bde000-24df-11ea-95f5-cb4cdf51bc18.png)

Minor Observations:
1. Some parts import all gray, even though opening their step file (or via File | Import) is as colorful as you might expect (same behavior as prior versions).
2) Some information printed in black, not white as expected.

**Comment by marmni** [comment]
Nice to hear that :).

Ad. 2 - Have you set the 'Annotation' color in the settings? Edit->Preferences->PCB->Colors

![2019_12_23_15_20_07_Window](https://user-images.githubusercontent.com/10199795/71362918-c4302380-2597-11ea-89e9-bb4b2912be75.png)

Ad. 1 - There are few ways to solve this - because this is not a bug in PCB workbench.

Step 1. If you load *.step file to FC and you see colors -> you need to delete *.col file for mentioned model. Find part in the 'Assign models' window and use function -> 'Delete *. col files' (and reload board). Skip step 2 (if it helped).
Step 2. If you load *.step file to FC and you do not see colors -> you need to change STP export format: Edit->Preferences->Import-Export->STEP-> and select AP203. Load *.fcstd and export it as STEP with colors. Then follow step 1.

**Comment by Wiredhome** [comment]
With your hints - I've learned a lot! More accurate presentation. Correct silk color (I had thought it would pull it from the .brd file).

![Reflow](https://user-images.githubusercontent.com/13155300/71389665-f5721900-25c2-11ea-9df3-92bfaf16b612.png)
Thanks again!

**Comment by Wiredhome** [comment]
With your guidance - it just keeps getting and looking better.
![Reflow](https://user-images.githubusercontent.com/13155300/71390000-2dc62700-25c4-11ea-8952-207e3a9ae188.png)

Should I append other observations here, or open a new item?

**Comment by marmni** [comment]
Hi,
I prefer one problem/proposal one topic - it is easier to manage them later.

**Comment by marmni** [comment]
Done. Version for FC_0.18 and Py_3.6.

**Comment by luzpaz** [comment]
@marmni it's not necessary to update the revision but I will do so anyway :)
