### ISSUE TITLE
Importing Allegro ECAD files to Free CAD software

### ISSUE THREAD

**Issue by akshaycj1** [marmni/FreeCAD-PCB#41]
I am planning to use Free CAD software for importing PCB files. My electrical CAD team uses Allegro software for rooting and placement. My doubt here is after installing PCB workbench, can I import files to Free CAD software and convert them to step files? My electrical CAD team can provide board files in IDF(emn, emp) and allegro .brd file format.

**Comment by marmni** [comment]
Hi,
"an I import files to Free CAD software and convert them to step files?"
Yes - and many other formats.

You can import IDF v2 and v3 (v4 is not supported). Allegro *.brd file format is not supported.
