### ISSUE TITLE
missing module named PCBcheckFreeCADVersion

### ISSUE THREAD

**Issue by luemmel76** [marmni/FreeCAD-PCB#5]
Hi, I wanted to test the FreeCAD-PCB-FC_0.18 version, but the message comes immediately:

`Traceback (most recent call last):
  File "<string>", line 120, in InitApplications
  File "<string>", line 176, in <module>
ImportError: No module named PCBcheckFreeCADVersion

During initialization the error No module named PCBcheckFreeCADVersion occurred in F:\FreeCAD18\Mod\PCB\InitGui.py
Please look into the log file for further information

global name 'PCBcheckFreeCADVersion' is not defined
Traceback (most recent call last):
  File "<string>", line 115, in Initialize`

**Comment by marmni** [comment]
Hi,
I know about this error, I just forgot to upload/update all files :). I will do it in a few minutes.

**Comment by marmni** [comment]
Ok, done. Please replace file data/database.cfg by your file (do backup).
