### ISSUE TITLE
Missing compatibility with FreeCAD Link Stage / Link Daily Editions (Supported FreeCAD versions: 0.18-0.19)

### ISSUE THREAD

**Issue by eduncan911** [marmni/FreeCAD-PCB#55]
We cannot use this workbench with realthunder's LinkDaily/LinkStage editions.  Upon loading, there's an ***invalid*** error that says:

    PCB Workbench: Error. Incompatible FreeCAD version. Supported FreeCAD versions: 0.18-0.19.

This has been going on for over a year.  realthunder's branch is mostly kept up-to-date with FreeCAD master, which is currently 0.20.  But this was not working even with older 0.19 mainline in FreeCAD master.

*This is the only Workbench that prevents itself from loading with an erroneous check for a version.*

Suggestions:

- Remove the version check.  It's not needed.
- Or, move the Error to a Warning instead, and allow the workbench to load anyways.

**Comment by marmni** [comment]
Hi, changed to a warning.
